project_name: AIC_swint
exp_name: T400
use_wandb: False
wandb_entity: qbyjj
train_root: /root/autodl-tmp/webfg400_train/train
val_ratio: 0.2
val_root: ~
data_size: 224
num_workers: 8
batch_size: 80
model_name: swin-t
pretrained: /root/AIC-CGL-/records/AIC_swint/T400/backup/best.pt
optimizer: SGD
max_lr: 0.0005
wdecay: 0.0005
max_epochs: 100
warmup_batchs: 1200
use_amp: True
use_fpn: True
fpn_size: 512
use_selection: True
num_classes: 400
num_classes_coarse: 10
finegrain: False
num_selects: 
  layer1: 256
  layer2: 128
  layer3: 64
  layer4: 32
use_combiner: True
lambda_b: 0.5
lambda_s: 0.5
lambda_n: 0.1
lambda_c: 2.0
update_freq: 1
log_freq: 50
eval_freq: 1