project_name: MTARSI_vit
exp_name: vit
use_wandb: False
wandb_entity: qbyjj
train_root: /root/autodl-tmp/webfg400_train/train/
val_root: ~
data_size: 384
num_workers: 12
batch_size: 30
model_name: vit
pretrained: /root/AIC/CGL/records/MTARSI_vit/vit/backup/last.pt
optimizer: SGD
max_lr: 0.001
wdecay: 0.0005
max_epochs: 200
warmup_batchs: 800
use_amp: True
use_fpn: True
fpn_size: 768
use_selection: True
num_classes: 400
num_classes_coarse: 10
finegrain: False
num_selects: 
  layer1: 512
  layer2: 256
  layer3: 128
  layer4: 32
use_combiner: True
lambda_b: 0.1
lambda_s: 0.0
lambda_n: 1.0
lambda_c: 1.0
update_freq: 1
log_freq: 100
eval_freq: 2
