project_name: AIC_swint
exp_name: T400
use_wandb: False
wandb_entity: qbyjj
train_root: E:/FineGrained/datasets/FGVC-Aircrafts/train/
val_root: ~
data_size: 224
num_workers: 12
batch_size: 200
model_name: swin-t
pretrained: ~
optimizer: SGD
max_lr: 0.0005
wdecay: 0.0005
max_epochs: 50
warmup_batchs: 800
use_amp: True
use_fpn: True
fpn_size: 512
use_selection: True
num_classes: 400
num_classes_coarse: 10
finegrain: False
num_selects: 
  layer1: 256
  layer2: 128
  layer3: 64
  layer4: 32
use_combiner: True
lambda_b: 0.5
lambda_s: 0.5
lambda_n: 0.0
lambda_c: 1.0
update_freq: 1
log_freq: 20
eval_freq: 1