project_name: MTARSI_swint
exp_name: T2.0
use_wandb: False
wandb_entity: qbyjj
train_root: D:\iLoveCoding\PythonCode\CGL\CGL\dataset\webfg400_train\
val_root: ~
data_size: 384
num_workers: 1
batch_size: 8
model_name: swin-t
pretrained: ~
optimizer: SGD
max_lr: 0.001
wdecay: 0.0005
max_epochs: 20
warmup_batchs: 800
use_amp: True
use_fpn: True
fpn_size: 1536
use_selection: True
num_classes: 400
num_classes_coarse: 10
finegrain: False
num_selects: 
  layer1: 2048
  layer2: 512
  layer3: 128
  layer4: 32
use_combiner: True
lambda_b: 0.5
lambda_s: 0.0
lambda_n: 5.0
lambda_c: 1.0
update_freq: 2
log_freq: 100
eval_freq: 10